import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
const weaponSource = readFileSync(new URL('../src/game/weapons.js', import.meta.url),'utf8');
const definitions = weaponSource.slice(weaponSource.indexOf('export const GUNS'), weaponSource.indexOf('/* Auto-fire')).replaceAll('export ', '');
const armorySource = readFileSync(new URL('../src/game/armory.js', import.meta.url),'utf8').replace(/^import .*\n/gm, '').replaceAll('export ', '');
const storage = new Map();
const elements = new Map();
const element = () => ({ textContent:'', innerHTML:'', open:false, addEventListener(){}, focus(){}, showModal(){this.open=true},close(){this.open=false} });
// armory.js saves through the platform storage shim (src/core/platform.js), so
// that is what the sandbox has to provide — localStorage is no longer touched.
const store = {getItem(k){return storage.get(k) ?? null},setItem(k,v){storage.set(k,String(v))},removeItem(k){storage.delete(k)}};
const context = vm.createContext({gunIllustration(){return ''},document:{getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id)}},storage:store,localStorage:store});
vm.runInContext(definitions + armorySource + '\nglobalThis.Armory = Armory; globalThis.GUNS=GUNS;', context);
const color = () => ({set(){}});
const player = {equipGun(){},pos:{x:0,z:0},gun:{material:{color:color()}},muzzle:{material:{emissive:color()}},mats:[],vel:{x:0,z:0,set(){}}};
let equipped;
const weapon = {equip(g,l){equipped={id:g.id,level:l}}};
const input = {keys:new Set(),stickEl:{classList:{remove(){}}}};
const a = new context.Armory(weapon,player,input);
assert.equal(context.GUNS.length,5);
assert.equal(a.coins,120,'fresh players receive exactly the first laser upgrade cost');
a.open();assert.equal(a.paused,false,'cannot open away from station');
for(let i=0;i<119;i++)a.update(1/60,{store:{x:0,z:0}},'fight');
assert.equal(a.paused,false,'must wait full two seconds');
a.update(0.05,{store:{x:0,z:0}},'fight');assert.equal(a.paused,true);
assert.equal(a.act('plasma','buy'),false);
assert.equal(a.act('rail','equip'),false);
a.earn(1130); assert.equal(a.act('scatter','buy'),true); assert.equal(a.coins,0); assert.equal(equipped.id,'scatter');
assert.equal(a.act('scatter','buy'),false);
a.earn(50000);
for(let i=0;i<4;i++) assert.equal(a.act('scatter','upgrade'),true);
const coins = a.coins;
assert.equal(a.levels.scatter,5); assert.equal(a.act('scatter','upgrade'),false); assert.equal(a.coins,coins);
for(const id of ['rapid','rail','plasma']) assert.equal(a.act(id,'buy'),true);
a.open(); assert.equal(a.paused,true); a.close(); assert.equal(a.paused,false);
a.update(3,{store:{x:0,z:0}},'fight'); assert.equal(a.paused,false,'does not immediately reopen');
player.pos.x=10;a.update(.1,{store:{x:0,z:0}},'fight');player.pos.x=0;
a.update(1,{store:{x:0,z:0}},'fight');player.vel.x=2;a.update(.1,{store:{x:0,z:0}},'fight');
assert.equal(a.dwell,0,'movement resets timer');player.vel.x=0;a.update(2,{store:{x:0,z:0}},'fight');assert.equal(a.paused,true,'can revisit');
const restored = new context.Armory(weapon,player,input);
assert.equal(restored.selected,'plasma'); assert.equal(restored.coins,a.coins); assert.equal(restored.levels.scatter,5);
storage.set('verdant.armory.v1','{broken'); assert.doesNotThrow(()=>new context.Armory(weapon,player,input));
storage.set('verdant.armory.v1',JSON.stringify({coins:-100,selected:'unknown',levels:{laser:99,plasma:-2}}));
const sanitized = new context.Armory(weapon,player,input);
assert.equal(sanitized.coins,0); assert.equal(sanitized.selected,'laser'); assert.equal(sanitized.levels.laser,5); assert.equal(sanitized.levels.plasma,0);
console.log('PASS: five guns, insufficient funds, ownership, purchase deductions, upgrade cap, equip, pause, persistence, invalid saves');
